### ISSUE TITLE
Can not import gjson==1.0.0  for python3.8

### ISSUE THREAD

**Issue by sc0der** [volans-/gjson-py#5]
`import gjson`

Getting this error while importing the package for python3.8 but it works for python3.10

Error:
![carbon](https://github.com/volans-/gjson-py/assets/44986984/1670d630-8f52-4b4a-bc8c-a710edcde5a2)

**Comment by volans-** [comment]
Hi @sc0der, as stated in the package's metadata on [PyPi](https://pypi.org/project/gjson/) and in `setup.py` gjson does require python 3.9 or higher. Python 3.8 is fairly old and currently only receiving security fixes and will be end of life in few months. Gjson uses features only available in python 3.9+, I'm sorry.
