### ISSUE TITLE
missing value when multipath contains nonexistent key

### ISSUE THREAD

**Issue by flaribbit** [volans-/gjson-py#6]
Hello, I got a problem while using this library in my project. The minimum reproducible code is as follows:

```python
import gjson

data = gjson.GJSON({"a": 2, "c": 4})

print(data.get("b", quiet=True))  # None, as expected
print(data.get("[a,b,c]", quiet=True))  # expected: [2, None, 4], but got [2, 4]
```

Is this a bug or the intended behavior?

**Comment by volans-** [comment]
@flaribbit that's the actual behavior of upstream GJSON, as you can see in https://gjson.dev/ for example.

**Comment by flaribbit** [comment]
Thank you for your reply. I see. Thinking about it, it makes sense when packing the result into a list. I'll keep that in mind. Thanks again!
